mysql:
  #container_name: flask_mysql
  restart: always
  image: mysql:latest
  volumes:
    - ./init.sql:/docker-entrypoint-initdb.d/init.sql  
    - /opt/mysql_data:/var/lib/mysql
  environment:
    MYSQL_ROOT_PASSWORD: password
    MYSQL_DATABASE: test
    #MYSQL_USER: root
    MYSQL_PASSWORD: password
  ports:
    - "3306:3306"
api:
  image: contract-api
  ports:
    - "8080:8080"
  environment:
    SPRING_DATASOURCE_URL: jdbc:mysql://mysql/test
  links:
    - mysql